"""Financial health alerts ORM model.

Alerts are scoped to an organization (multi-tenant) and generated by the AI
accounting engine when it detects anomalies or important events.
"""
from __future__ import annotations

import enum
import uuid
from datetime import datetime

from sqlalchemy import (
    DateTime,
    Enum,
    ForeignKey,
    Index,
    String,
    text,
)
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base
from app.db.models._utils import utcnow


class AlertSeverity(str, enum.Enum):
    high = "high"
    normal = "normal"
    low = "low"


class Alert(Base):
    """Dynamic financial health alert for an organization."""

    __tablename__ = "alerts"

    id: Mapped[str] = mapped_column(primary_key=True, default=lambda: uuid.uuid4().hex)
    organization_id: Mapped[str] = mapped_column(
        PGUUID(as_uuid=False),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str] = mapped_column(String(1000), nullable=False)
    type: Mapped[str] = mapped_column(String(100), nullable=False)
    severity_level: Mapped[AlertSeverity] = mapped_column(
        Enum(AlertSeverity, name="alert_severity", native_enum=True),
        nullable=False,
    )
    trigger_source: Mapped[str] = mapped_column(String(100), nullable=False)
    resolved_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True, default=None
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=utcnow, server_default=text("now()")
    )

    organization: Mapped[object] = relationship("Organization")

    __table_args__ = (
        Index("ix_alerts_organization_id", "organization_id"),
        Index("ix_alerts_type", "type"),
        Index("ix_alerts_severity_level", "severity_level"),
        Index("ix_alerts_resolved_at", "resolved_at"),
    )
