"""init schema

Revision ID: 02b2898b427b
Revises:
Create Date: 2025-10-30 11:12:41.145182

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "02b2898b427b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bank_accounts", sa.Column("external_connection_id", sa.UUID(), nullable=False)
    )
    op.drop_constraint(
        op.f("bank_accounts_external_id_key"), "bank_accounts", type_="unique"
    )
    op.create_unique_constraint(
        "uq_accounts_ext_per_conn",
        "bank_accounts",
        ["external_id", "external_connection_id"],
    )
    op.create_unique_constraint(
        op.f("uq_bank_accounts_external_id"), "bank_accounts", ["external_id"]
    )
    op.create_foreign_key(
        op.f("fk_bank_accounts_connection_id_connections"),
        "bank_accounts",
        "connections",
        ["connection_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "businesses",
        "is_onboarding_complete",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("connections_external_id_key"), "connections", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_connections_external_id"), "connections", ["external_id"]
    )
    op.drop_constraint(op.f("consents_external_id_key"), "consents", type_="unique")
    op.create_unique_constraint(
        op.f("uq_consents_external_id"), "consents", ["external_id"]
    )
    op.alter_column(
        "documents",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "onboarding_sessions",
        "business_id",
        existing_type=sa.VARCHAR(length=32),
        nullable=False,
    )
    op.alter_column(
        "onboarding_sessions",
        "phone_verified_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "onboarding_sessions",
        "email_verified_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "onboarding_sessions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "onboarding_sessions",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        "ix_onboarding_status", "onboarding_sessions", ["status"], unique=False
    )
    op.create_index("ix_onboarding_step", "onboarding_sessions", ["step"], unique=False)
    op.alter_column(
        "seller_profiles",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("seller_profiles_email_key"), "seller_profiles", type_="unique"
    )
    op.drop_constraint(
        op.f("seller_profiles_phone_number_key"), "seller_profiles", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_seller_profiles_email"), "seller_profiles", ["email"]
    )
    op.create_unique_constraint(
        op.f("uq_seller_profiles_phone_number"), "seller_profiles", ["phone_number"]
    )
    op.alter_column(
        "verification_sessions",
        "onboarding_session_id",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=32),
        existing_nullable=False,
    )
    op.alter_column(
        "verification_sessions",
        "sent_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "verification_sessions",
        "last_sent_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "verification_sessions",
        "expires_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "verification_sessions",
        "used_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conname = 'verification_sessions_verification_id_key'
            ) THEN
                ALTER TABLE verification_sessions
                ADD CONSTRAINT verification_sessions_verification_id_key UNIQUE (verification_id);
            END IF;
        END $$;
        """
    )
    op.create_index(
        "ix_verification_channel", "verification_sessions", ["channel"], unique=False
    )
    op.create_index(
        op.f("ix_verification_sessions_onboarding_session_id"),
        "verification_sessions",
        ["onboarding_session_id"],
        unique=False,
    )
    op.create_index("ix_business_phone", "businesses", ["phone_number"], unique=False)

    op.create_index(
        "ix_connections_external_customer_id",
        "connections",
        ["external_customer_id"],
        unique=False,
    )
    op.create_index(
        "ix_connections_provider_code", "connections", ["provider_code"], unique=False
    )
    op.create_index("ix_connections_status", "connections", ["status"], unique=False)
    op.create_index(
        "ix_connections_auto_refresh",
        "connections",
        ["automatic_refresh"],
        unique=False,
    )
    op.create_index(
        "ix_consents_connection_id", "consents", ["connection_id"], unique=False
    )
    op.create_index("ix_consents_status", "consents", ["status"], unique=False)
    op.create_index("ix_consents_expires_at", "consents", ["expires_at"], unique=False)
    op.create_index(
        "ix_consents_scopes_gin",
        "consents",
        ["scopes"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_onboarding_sessions_business_id"),
        "onboarding_sessions",
        ["business_id"],
        unique=False,
    )
    op.create_index("ix_business_email", "businesses", ["email"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_verification_sessions_onboarding_session_id"),
        table_name="verification_sessions",
    )
    op.drop_index("ix_verification_channel", table_name="verification_sessions")
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conname = 'verification_sessions_verification_id_key'
            ) THEN
                ALTER TABLE verification_sessions
                DROP CONSTRAINT verification_sessions_verification_id_key;
            END IF;
        END $$;
    """
    )
    op.alter_column(
        "verification_sessions",
        "used_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "verification_sessions",
        "expires_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "verification_sessions",
        "last_sent_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "verification_sessions",
        "sent_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "verification_sessions",
        "onboarding_session_id",
        existing_type=sa.String(length=32),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("uq_seller_profiles_phone_number"), "seller_profiles", type_="unique"
    )
    op.drop_constraint(
        op.f("uq_seller_profiles_email"), "seller_profiles", type_="unique"
    )
    op.create_unique_constraint(
        op.f("seller_profiles_phone_number_key"),
        "seller_profiles",
        ["phone_number"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("seller_profiles_email_key"),
        "seller_profiles",
        ["email"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "seller_profiles",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=False,
    )
    op.drop_index("ix_onboarding_step", table_name="onboarding_sessions")
    op.drop_index("ix_onboarding_status", table_name="onboarding_sessions")
    op.alter_column(
        "onboarding_sessions",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "onboarding_sessions",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "onboarding_sessions",
        "email_verified_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "onboarding_sessions",
        "phone_verified_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "onboarding_sessions",
        "business_id",
        existing_type=sa.VARCHAR(length=32),
        nullable=True,
    )
    op.alter_column(
        "documents",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(op.f("uq_consents_external_id"), "consents", type_="unique")
    op.create_unique_constraint(
        op.f("consents_external_id_key"),
        "consents",
        ["external_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint(
        op.f("uq_connections_external_id"), "connections", type_="unique"
    )
    op.create_unique_constraint(
        op.f("connections_external_id_key"),
        "connections",
        ["external_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "businesses",
        "is_onboarding_complete",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("fk_bank_accounts_connection_id_connections"),
        "bank_accounts",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("uq_bank_accounts_external_id"), "bank_accounts", type_="unique"
    )
    op.drop_constraint("uq_accounts_ext_per_conn", "bank_accounts", type_="unique")
    op.create_unique_constraint(
        op.f("bank_accounts_external_id_key"),
        "bank_accounts",
        ["external_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("bank_accounts", "external_connection_id")

    op.drop_index(
        op.f("ix_onboarding_sessions_business_id"), table_name="onboarding_sessions"
    )

    # consents
    op.drop_index("ix_consents_scopes_gin", table_name="consents")
    op.drop_index("ix_consents_expires_at", table_name="consents")
    op.drop_index("ix_consents_status", table_name="consents")
    op.drop_index("ix_consents_connection_id", table_name="consents")

    # connections
    op.drop_index("ix_connections_auto_refresh", table_name="connections")
    op.drop_index("ix_connections_status", table_name="connections")
    op.drop_index("ix_connections_provider_code", table_name="connections")
    op.drop_index("ix_connections_external_customer_id", table_name="connections")

    # businesses
    op.drop_index("ix_business_phone", table_name="businesses")
    op.drop_index("ix_business_email", table_name="businesses")
    op.drop_index("ix_business_email", table_name="businesses")
    # ### end Alembic commands ###
