"""Initial schema creation

Revision ID: 1bf2ae9903b6
Revises: 
Create Date: 2026-03-22 12:55:00.678725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1bf2ae9903b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bucket', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('public_url', sa.String(), nullable=True),
    sa.Column('_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_table('organizations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vat_number', sa.String(length=30), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False, comment='ISO 3166-1 alpha-2'),
    sa.Column('registry_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_index('ix_organizations_vat_country', 'organizations', ['vat_number', 'country'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('bic_codes', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('identification_codes', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('dynamic_registration_code', sa.String(), nullable=True),
    sa.Column('group_code', sa.String(), nullable=True),
    sa.Column('group_name', sa.String(), nullable=True),
    sa.Column('hub', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('regulated', sa.Boolean(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('supported_iframe_embedding', sa.Boolean(), nullable=False),
    sa.Column('optional_interactivity', sa.Boolean(), nullable=True),
    sa.Column('customer_notified_on_sign_in', sa.Boolean(), nullable=False),
    sa.Column('automatic_fetch', sa.Boolean(), nullable=True),
    sa.Column('custom_pendings_period', sa.Integer(), nullable=True),
    sa.Column('holder_info', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('instruction_for_connections', sa.String(), nullable=True),
    sa.Column('interactive_for_connections', sa.Boolean(), nullable=True),
    sa.Column('max_consent_days', sa.Integer(), nullable=True),
    sa.Column('max_fetch_interval', sa.Integer(), nullable=True),
    sa.Column('fetch_policies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('max_interactive_delay', sa.Integer(), nullable=True),
    sa.Column('refresh_timeout', sa.Integer(), nullable=True),
    sa.Column('supported_account_extra_fields', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('supported_account_natures', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('supported_account_types', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('supported_fetch_scopes', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('supported_transaction_extra_fields', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('payment_templates', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('instruction_for_payments', sa.String(), nullable=True),
    sa.Column('interactive_for_payments', sa.Boolean(), nullable=True),
    sa.Column('no_funds_rejection_supported', sa.Boolean(), nullable=True),
    sa.Column('required_payment_fields', sa.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('supported_payment_fields', sa.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('credentials_fields', sa.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('interactive_fields', sa.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mode IN ('oauth', 'web', 'api')", name=op.f('ck_providers_provider_mode_chk')),
    sa.CheckConstraint("status IN ('active', 'inactive', 'disabled')", name=op.f('ck_providers_provider_status_chk')),
    sa.CheckConstraint('char_length(country_code) = 2', name=op.f('ck_providers_provider_country_code_len_2')),
    sa.CheckConstraint('country_code = upper(country_code)', name=op.f('ck_providers_provider_country_code_upper')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_providers'))
    )
    op.create_index(op.f('ix_providers_code'), 'providers', ['code'], unique=True)
    op.create_index('ix_providers_country_code', 'providers', ['country_code'], unique=False)
    op.create_index('ix_providers_mode', 'providers', ['mode'], unique=False)
    op.create_index('ix_providers_regulated', 'providers', ['regulated'], unique=False)
    op.create_index('ix_providers_status', 'providers', ['status'], unique=False)
    op.create_table('aade_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('raw_xml', sa.Text(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('query_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('continuation_token', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_aade_documents_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aade_documents'))
    )
    op.create_index('ix_aade_documents_fetched_at', 'aade_documents', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_aade_documents_organization_id'), 'aade_documents', ['organization_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('severity_level', sa.Enum('high', 'normal', 'low', name='alert_severity'), nullable=False),
    sa.Column('trigger_source', sa.String(length=100), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_alerts_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index(op.f('ix_alerts_organization_id'), 'alerts', ['organization_id'], unique=False)
    op.create_index('ix_alerts_resolved_at', 'alerts', ['resolved_at'], unique=False)
    op.create_index('ix_alerts_severity_level', 'alerts', ['severity_level'], unique=False)
    op.create_index('ix_alerts_type', 'alerts', ['type'], unique=False)
    op.create_table('counterparties',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vat_number', sa.String(length=30), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True, comment='ISO 3166-1 alpha-2'),
    sa.Column('address_street', sa.String(length=255), nullable=True),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('address_postal_code', sa.String(length=20), nullable=True),
    sa.Column('address_region', sa.String(length=100), nullable=True),
    sa.Column('type', sa.Enum('CUSTOMER', 'VENDOR', 'BOTH', name='counterpartytype'), nullable=False),
    sa.Column('contact_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('default_category_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('registry_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_counterparties_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_counterparties'))
    )
    op.create_index('ix_counterparties_deleted_at', 'counterparties', ['deleted_at'], unique=False)
    op.create_index('ix_counterparties_organization_id', 'counterparties', ['organization_id'], unique=False)
    op.create_index('ix_counterparties_vat_number', 'counterparties', ['vat_number'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('categorization_type', sa.String(), nullable=False),
    sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('kyc', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("categorization_type IN ('personal', 'business')", name=op.f('ck_customers_customer_categorization_chk')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_customers_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('email', name='uq_customers_email'),
    sa.UniqueConstraint('external_id', name=op.f('uq_customers_external_id')),
    sa.UniqueConstraint('identifier', name='uq_customers_identifier')
    )
    op.create_index('ix_customers_email', 'customers', ['email'], unique=False)
    op.create_index('ix_customers_identifier', 'customers', ['identifier'], unique=False)
    op.create_index('ix_customers_organization_id', 'customers', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'EXTERNAL_ACCOUNTANT', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('password_reset_token', sa.String(length=64), nullable=True),
    sa.Column('password_reset_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id_organizations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('google_id', name=op.f('uq_users_google_id')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_google_id', 'users', ['google_id'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('aade_invoices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.Enum('RECEIVED', 'TRANSMITTED', name='invoice_direction'), nullable=False),
    sa.Column('uid', sa.String(length=100), nullable=True),
    sa.Column('mark', sa.BigInteger(), nullable=True),
    sa.Column('authentication_code', sa.String(length=200), nullable=True),
    sa.Column('issuer_vat', sa.String(length=20), nullable=True),
    sa.Column('issuer_country', sa.String(length=2), nullable=True),
    sa.Column('issuer_branch', sa.Integer(), nullable=True),
    sa.Column('counterpart_vat', sa.String(length=20), nullable=True),
    sa.Column('counterpart_country', sa.String(length=2), nullable=True),
    sa.Column('counterpart_branch', sa.Integer(), nullable=True),
    sa.Column('series', sa.String(length=50), nullable=True),
    sa.Column('aa', sa.String(length=50), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('invoice_type', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('total_net_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_vat_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_gross_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('normalized_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['aade_documents.id'], name=op.f('fk_aade_invoices_document_id_aade_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_aade_invoices_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aade_invoices')),
    sa.UniqueConstraint('mark', name=op.f('uq_aade_invoices_mark'))
    )
    op.create_index(op.f('ix_aade_invoices_counterpart_vat'), 'aade_invoices', ['counterpart_vat'], unique=False)
    op.create_index(op.f('ix_aade_invoices_document_id'), 'aade_invoices', ['document_id'], unique=False)
    op.create_index(op.f('ix_aade_invoices_invoice_type'), 'aade_invoices', ['invoice_type'], unique=False)
    op.create_index('ix_aade_invoices_issue_date', 'aade_invoices', ['issue_date'], unique=False)
    op.create_index('ix_aade_invoices_issuer_vat', 'aade_invoices', ['issuer_vat'], unique=False)
    op.create_index(op.f('ix_aade_invoices_organization_id'), 'aade_invoices', ['organization_id'], unique=False)
    op.create_index(op.f('ix_aade_invoices_uid'), 'aade_invoices', ['uid'], unique=False)
    op.create_table('connections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('external_customer_id', sa.String(), nullable=False),
    sa.Column('customer_identifier', sa.String(), nullable=True),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('provider_code', sa.String(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('categorization', sa.String(), nullable=False),
    sa.Column('categorization_vendor', sa.String(), nullable=True),
    sa.Column('automatic_refresh', sa.Boolean(), nullable=False),
    sa.Column('next_refresh_possible_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_consent_id', sa.String(), nullable=False),
    sa.Column('last_attempt', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('holder_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("categorization IN ('none', 'personal', 'business')", name=op.f('ck_connections_connection_cat_chk')),
    sa.CheckConstraint("status IN ('active', 'inactive', 'disabled')", name=op.f('ck_connections_connection_status_chk')),
    sa.CheckConstraint('char_length(country_code) = 2', name=op.f('ck_connections_country_code_len_2')),
    sa.CheckConstraint('country_code = upper(country_code)', name=op.f('ck_connections_country_code_upper')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_connections_customer_id_customers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connections')),
    sa.UniqueConstraint('external_id', name=op.f('uq_connections_external_id'))
    )
    op.create_index('ix_connections_auto_refresh', 'connections', ['automatic_refresh'], unique=False)
    op.create_index('ix_connections_external_customer_id', 'connections', ['external_customer_id'], unique=False)
    op.create_index('ix_connections_provider_code', 'connections', ['provider_code'], unique=False)
    op.create_index('ix_connections_status', 'connections', ['status'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('jti_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_user_sessions_token_hash'))
    )
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index('ix_user_sessions_token_hash', 'user_sessions', ['token_hash'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('bank_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('external_connection_id', sa.String(), nullable=False),
    sa.Column('connection_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nature', sa.String(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint('char_length(currency_code) = 3', name=op.f('ck_bank_accounts_currency_code_len_3')),
    sa.CheckConstraint('currency_code = upper(currency_code)', name=op.f('ck_bank_accounts_currency_code_uppercase')),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], name=op.f('fk_bank_accounts_connection_id_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_bank_accounts_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_accounts')),
    sa.UniqueConstraint('external_id', 'external_connection_id', name='uq_accounts_ext_per_conn'),
    sa.UniqueConstraint('external_id', name=op.f('uq_bank_accounts_external_id'))
    )
    op.create_index('ix_bank_accounts_organization_id', 'bank_accounts', ['organization_id'], unique=False)
    op.create_table('consents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('external_customer_id', sa.String(), nullable=False),
    sa.Column('external_connection_id', sa.String(), nullable=False),
    sa.Column('connection_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('scopes', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('period_days', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('from_date', sa.Date(), nullable=True),
    sa.Column('to_date', sa.Date(), nullable=True),
    sa.Column('collected_by', sa.String(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(collected_by IS NULL) OR (collected_by IN ('client', 'saltedge'))", name=op.f('ck_consents_consent_collected_by_chk')),
    sa.CheckConstraint("(revoke_reason IS NULL) OR (revoke_reason IN ('expired', 'client', 'provider', 'saltedge'))", name=op.f('ck_consents_consent_revoke_reason_chk')),
    sa.CheckConstraint("status IN ('active', 'expired', 'revoked')", name=op.f('ck_consents_consent_status_chk')),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], name=op.f('fk_consents_connection_id_connections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consents')),
    sa.UniqueConstraint('external_id', name=op.f('uq_consents_external_id'))
    )
    op.create_index('ix_consents_connection_id', 'consents', ['connection_id'], unique=False)
    op.create_index('ix_consents_expires_at', 'consents', ['expires_at'], unique=False)
    op.create_index('ix_consents_scopes_gin', 'consents', ['scopes'], unique=False)
    op.create_index('ix_consents_status', 'consents', ['status'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('posted', 'pending', name='transaction_status'), nullable=False),
    sa.Column('mode', sa.Enum('normal', 'fee', 'transfer', name='transaction_mode'), nullable=False),
    sa.Column('duplicated', sa.Boolean(), nullable=False),
    sa.Column('made_on', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['bank_accounts.id'], name=op.f('fk_transactions_account_id_bank_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_transactions_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index('ix_transactions_account_made_on', 'transactions', ['account_id', 'made_on'], unique=False)
    op.create_index(op.f('ix_transactions_category'), 'transactions', ['category'], unique=False)
    op.create_index('ix_transactions_extra_gin', 'transactions', ['extra'], unique=False, postgresql_using='gin', postgresql_ops={'extra': 'jsonb_path_ops'})
    op.create_index(op.f('ix_transactions_made_on'), 'transactions', ['made_on'], unique=False)
    op.create_index('ix_transactions_made_on_posted_only', 'transactions', ['made_on'], unique=False, postgresql_where=False)
    op.create_index(op.f('ix_transactions_mode'), 'transactions', ['mode'], unique=False)
    op.create_index('ix_transactions_organization_id', 'transactions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index('ix_transactions_organization_id', table_name='transactions')
    op.drop_index(op.f('ix_transactions_mode'), table_name='transactions')
    op.drop_index('ix_transactions_made_on_posted_only', table_name='transactions', postgresql_where=False)
    op.drop_index(op.f('ix_transactions_made_on'), table_name='transactions')
    op.drop_index('ix_transactions_extra_gin', table_name='transactions', postgresql_using='gin', postgresql_ops={'extra': 'jsonb_path_ops'})
    op.drop_index(op.f('ix_transactions_category'), table_name='transactions')
    op.drop_index('ix_transactions_account_made_on', table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_consents_status', table_name='consents')
    op.drop_index('ix_consents_scopes_gin', table_name='consents')
    op.drop_index('ix_consents_expires_at', table_name='consents')
    op.drop_index('ix_consents_connection_id', table_name='consents')
    op.drop_table('consents')
    op.drop_index('ix_bank_accounts_organization_id', table_name='bank_accounts')
    op.drop_table('bank_accounts')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index('ix_user_sessions_token_hash', table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('ix_connections_status', table_name='connections')
    op.drop_index('ix_connections_provider_code', table_name='connections')
    op.drop_index('ix_connections_external_customer_id', table_name='connections')
    op.drop_index('ix_connections_auto_refresh', table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('ix_aade_invoices_uid'), table_name='aade_invoices')
    op.drop_index(op.f('ix_aade_invoices_organization_id'), table_name='aade_invoices')
    op.drop_index('ix_aade_invoices_issuer_vat', table_name='aade_invoices')
    op.drop_index('ix_aade_invoices_issue_date', table_name='aade_invoices')
    op.drop_index(op.f('ix_aade_invoices_invoice_type'), table_name='aade_invoices')
    op.drop_index(op.f('ix_aade_invoices_document_id'), table_name='aade_invoices')
    op.drop_index(op.f('ix_aade_invoices_counterpart_vat'), table_name='aade_invoices')
    op.drop_table('aade_invoices')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index('ix_users_google_id', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_customers_organization_id', table_name='customers')
    op.drop_index('ix_customers_identifier', table_name='customers')
    op.drop_index('ix_customers_email', table_name='customers')
    op.drop_table('customers')
    op.drop_index('ix_counterparties_vat_number', table_name='counterparties')
    op.drop_index('ix_counterparties_organization_id', table_name='counterparties')
    op.drop_index('ix_counterparties_deleted_at', table_name='counterparties')
    op.drop_table('counterparties')
    op.drop_index('ix_alerts_type', table_name='alerts')
    op.drop_index('ix_alerts_severity_level', table_name='alerts')
    op.drop_index('ix_alerts_resolved_at', table_name='alerts')
    op.drop_index(op.f('ix_alerts_organization_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_aade_documents_organization_id'), table_name='aade_documents')
    op.drop_index('ix_aade_documents_fetched_at', table_name='aade_documents')
    op.drop_table('aade_documents')
    op.drop_index('ix_providers_status', table_name='providers')
    op.drop_index('ix_providers_regulated', table_name='providers')
    op.drop_index('ix_providers_mode', table_name='providers')
    op.drop_index('ix_providers_country_code', table_name='providers')
    op.drop_index(op.f('ix_providers_code'), table_name='providers')
    op.drop_table('providers')
    op.drop_index('ix_organizations_vat_country', table_name='organizations')
    op.drop_table('organizations')
    op.drop_table('documents')
    # ### end Alembic commands ###
