"""Change aade_invoices.mark to BigInteger

Revision ID: 2e5efb7d262c
Revises: b5c8d9e2f1a3
Create Date: 2025-11-13 12:48:32.371079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e5efb7d262c'
down_revision: Union[str, Sequence[str], None] = 'b5c8d9e2f1a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aade_documents', 'raw_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('aade_documents', 'query_params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('aade_invoices', 'mark',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('aade_invoices', 'normalized_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_onboarding_tokens_token'), table_name='onboarding_tokens')
    op.create_index(op.f('ix_onboarding_tokens_token'), 'onboarding_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onboarding_tokens_token'), table_name='onboarding_tokens')
    op.create_index(op.f('ix_onboarding_tokens_token'), 'onboarding_tokens', ['token'], unique=False)
    op.alter_column('aade_invoices', 'normalized_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('aade_invoices', 'mark',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('aade_documents', 'query_params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('aade_documents', 'raw_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    # ### end Alembic commands ###
