"""Small foreign key relationship fix and attribute type

Revision ID: 3a02d2336c09
Revises: a12ec6ca299d
Create Date: 2025-11-04 13:56:45.455027

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3a02d2336c09"
down_revision: Union[str, Sequence[str], None] = "a12ec6ca299d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("bank_accounts_external_id_key"), "bank_accounts", type_="unique"
    )
    op.create_unique_constraint(
        "uq_accounts_ext_per_conn",
        "bank_accounts",
        ["external_id", "external_connection_id"],
    )
    op.create_unique_constraint(
        op.f("uq_bank_accounts_external_id"), "bank_accounts", ["external_id"]
    )
    op.alter_column(
        "businesses",
        "is_onboarding_complete",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("connections_external_id_key"), "connections", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_connections_external_id"), "connections", ["external_id"]
    )
    op.drop_constraint(op.f("consents_external_id_key"), "consents", type_="unique")
    op.create_unique_constraint(
        op.f("uq_consents_external_id"), "consents", ["external_id"]
    )
    op.alter_column(
        "documents",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "onboarding_sessions",
        "business_id",
        existing_type=sa.VARCHAR(length=32),
        nullable=False,
    )
    op.alter_column(
        "onboarding_sessions",
        "phone_verified_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "onboarding_sessions",
        "email_verified_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "onboarding_sessions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "onboarding_sessions",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        "ix_onboarding_status", "onboarding_sessions", ["status"], unique=False
    )
    op.create_index("ix_onboarding_step", "onboarding_sessions", ["step"], unique=False)
    op.drop_constraint(op.f("uq_providers_code"), "providers", type_="unique")
    op.drop_index(op.f("ix_providers_code"), table_name="providers")
    op.create_index(op.f("ix_providers_code"), "providers", ["code"], unique=True)
    op.alter_column(
        "seller_profiles",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("seller_profiles_email_key"), "seller_profiles", type_="unique"
    )
    op.drop_constraint(
        op.f("seller_profiles_phone_number_key"), "seller_profiles", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_seller_profiles_email"), "seller_profiles", ["email"]
    )
    op.create_unique_constraint(
        op.f("uq_seller_profiles_phone_number"), "seller_profiles", ["phone_number"]
    )
    op.alter_column(
        "transactions",
        "id",
        existing_type=sa.UUID(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "transactions",
        "duplicated",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "transactions",
        "currency_code",
        existing_type=sa.VARCHAR(length=3),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "transactions",
        "extra",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "verification_sessions",
        "onboarding_session_id",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=32),
        existing_nullable=False,
    )
    op.alter_column(
        "verification_sessions",
        "sent_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "verification_sessions",
        "last_sent_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "verification_sessions",
        "expires_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "verification_sessions",
        "used_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.drop_index(
        op.f("ix_verification_onboarding"), table_name="verification_sessions"
    )
    op.drop_constraint(
        op.f("verification_sessions_verification_id_key"),
        "verification_sessions",
        type_="unique",
    )
    op.create_index(
        "ix_verification_channel", "verification_sessions", ["channel"], unique=False
    )
    op.create_index(
        op.f("ix_verification_sessions_onboarding_session_id"),
        "verification_sessions",
        ["onboarding_session_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_verification_sessions_onboarding_session_id"),
        table_name="verification_sessions",
    )
    op.drop_index("ix_verification_channel", table_name="verification_sessions")
    op.create_unique_constraint(
        op.f("verification_sessions_verification_id_key"),
        "verification_sessions",
        ["verification_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_verification_onboarding"),
        "verification_sessions",
        ["onboarding_session_id"],
        unique=False,
    )
    op.alter_column(
        "verification_sessions",
        "used_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "verification_sessions",
        "expires_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "verification_sessions",
        "last_sent_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "verification_sessions",
        "sent_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "verification_sessions",
        "onboarding_session_id",
        existing_type=sa.String(length=32),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "transactions",
        "extra",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text("'{}'::jsonb"),
        existing_nullable=False,
    )
    op.alter_column(
        "transactions",
        "currency_code",
        existing_type=sa.VARCHAR(length=3),
        server_default=sa.text("'EUR'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "transactions",
        "duplicated",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.alter_column(
        "transactions",
        "id",
        existing_type=sa.String(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("uq_seller_profiles_phone_number"), "seller_profiles", type_="unique"
    )
    op.drop_constraint(
        op.f("uq_seller_profiles_email"), "seller_profiles", type_="unique"
    )
    op.create_unique_constraint(
        op.f("seller_profiles_phone_number_key"),
        "seller_profiles",
        ["phone_number"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("seller_profiles_email_key"),
        "seller_profiles",
        ["email"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "seller_profiles",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_providers_code"), table_name="providers")
    op.create_index(op.f("ix_providers_code"), "providers", ["code"], unique=False)
    op.create_unique_constraint(
        op.f("uq_providers_code"),
        "providers",
        ["code"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index("ix_onboarding_step", table_name="onboarding_sessions")
    op.drop_index("ix_onboarding_status", table_name="onboarding_sessions")
    op.alter_column(
        "onboarding_sessions",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "onboarding_sessions",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "onboarding_sessions",
        "email_verified_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "onboarding_sessions",
        "phone_verified_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "onboarding_sessions",
        "business_id",
        existing_type=sa.VARCHAR(length=32),
        nullable=True,
    )
    op.alter_column(
        "documents",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(op.f("uq_consents_external_id"), "consents", type_="unique")
    op.create_unique_constraint(
        op.f("consents_external_id_key"),
        "consents",
        ["external_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint(
        op.f("uq_connections_external_id"), "connections", type_="unique"
    )
    op.create_unique_constraint(
        op.f("connections_external_id_key"),
        "connections",
        ["external_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "businesses",
        "is_onboarding_complete",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("uq_bank_accounts_external_id"), "bank_accounts", type_="unique"
    )
    op.drop_constraint("uq_accounts_ext_per_conn", "bank_accounts", type_="unique")
    op.create_unique_constraint(
        op.f("bank_accounts_external_id_key"),
        "bank_accounts",
        ["external_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
