"""Change aade_invoices.mark to be unique

Revision ID: 3f46d120dd40
Revises: 2e5efb7d262c
Create Date: 2025-11-13 13:44:44.464009

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3f46d120dd40"
down_revision: Union[str, Sequence[str], None] = "2e5efb7d262c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_aade_invoices_mark"), "aade_invoices", ["mark"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_aade_invoices_mark"), "aade_invoices", type_="unique")
    # ### end Alembic commands ###
