"""add customers table link connections

Revision ID: ab2ffeb94b36
Revises: 02b2898b427b
Create Date: 2025-10-30 16:31:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ab2ffeb94b36"
down_revision: Union[str, None] = "02b2898b427b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create customers table
    op.create_table(
        "customers",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("identifier", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column(
            "categorization_type", sa.String(), nullable=False, default="personal"
        ),
        sa.Column("blocked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("kyc", postgresql.JSONB(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
        sa.UniqueConstraint("identifier", name="uq_customers_identifier"),
        sa.UniqueConstraint("email", name="uq_customers_email"),
        sa.CheckConstraint(
            "categorization_type IN ('personal', 'business')",
            name="customer_categorization_chk",
        ),
        sa.Index("ix_customers_identifier", "identifier"),
        sa.Index("ix_customers_email", "email"),
    )

    # Add customer_id column to connections table
    op.add_column(
        "connections",
        sa.Column("customer_id", postgresql.UUID(as_uuid=True), nullable=True),
    )

    # Create foreign key constraint
    op.create_foreign_key(
        op.f("fk_connections_customer_id_customers"),
        "connections",
        "customers",
        ["customer_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # Make customer_id not nullable after adding FK
    op.alter_column("connections", "customer_id", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key constraint
    op.drop_constraint(
        op.f("fk_connections_customer_id_customers"), "connections", type_="foreignkey"
    )

    # Drop customer_id column from connections
    op.drop_column("connections", "customer_id")

    # Drop customers table
    op.drop_table("customers")
    # ### end Alembic commands ###
