"""add providers table

Revision ID: add_providers_table
Revises: fix_bank_accounts_schema
Create Date: 2025-10-30 16:53:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "add_providers_table"
down_revision: Union[str, None] = "fix_bank_accounts_schema"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "providers",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("bic_codes", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("identification_codes", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("dynamic_registration_code", sa.String(), nullable=True),
        sa.Column("group_code", sa.String(), nullable=True),
        sa.Column("group_name", sa.String(), nullable=True),
        sa.Column("hub", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("mode", sa.String(), nullable=False),
        sa.Column("regulated", sa.Boolean(), nullable=False),
        sa.Column("logo_url", sa.String(), nullable=True),
        sa.Column("timezone", sa.String(), nullable=True),
        sa.Column("supported_iframe_embedding", sa.Boolean(), nullable=False),
        sa.Column("optional_interactivity", sa.Boolean(), nullable=True),
        sa.Column("customer_notified_on_sign_in", sa.Boolean(), nullable=False),
        sa.Column("automatic_fetch", sa.Boolean(), nullable=True),
        sa.Column("custom_pendings_period", sa.Integer(), nullable=True),
        sa.Column("holder_info", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("instruction_for_connections", sa.String(), nullable=True),
        sa.Column("interactive_for_connections", sa.Boolean(), nullable=True),
        sa.Column("max_consent_days", sa.Integer(), nullable=True),
        sa.Column("max_fetch_interval", sa.Integer(), nullable=True),
        sa.Column("fetch_policies", postgresql.JSONB(), nullable=True),
        sa.Column("max_interactive_delay", sa.Integer(), nullable=True),
        sa.Column("refresh_timeout", sa.Integer(), nullable=True),
        sa.Column(
            "supported_account_extra_fields",
            postgresql.ARRAY(sa.String()),
            nullable=True,
        ),
        sa.Column(
            "supported_account_natures", postgresql.ARRAY(sa.String()), nullable=True
        ),
        sa.Column(
            "supported_account_types", postgresql.ARRAY(sa.String()), nullable=True
        ),
        sa.Column(
            "supported_fetch_scopes", postgresql.ARRAY(sa.String()), nullable=True
        ),
        sa.Column(
            "supported_transaction_extra_fields",
            postgresql.ARRAY(sa.String()),
            nullable=True,
        ),
        sa.Column("payment_templates", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("instruction_for_payments", sa.String(), nullable=True),
        sa.Column("interactive_for_payments", sa.Boolean(), nullable=True),
        sa.Column("no_funds_rejection_supported", sa.Boolean(), nullable=True),
        sa.Column(
            "required_payment_fields",
            postgresql.ARRAY(postgresql.JSONB()),
            nullable=True,
        ),
        sa.Column(
            "supported_payment_fields",
            postgresql.ARRAY(postgresql.JSONB()),
            nullable=True,
        ),
        sa.Column(
            "credentials_fields", postgresql.ARRAY(postgresql.JSONB()), nullable=True
        ),
        sa.Column(
            "interactive_fields", postgresql.ARRAY(postgresql.JSONB()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.CheckConstraint(
            "char_length(country_code) = 2", name="provider_country_code_len_2"
        ),
        sa.CheckConstraint(
            "country_code = upper(country_code)", name="provider_country_code_upper"
        ),
        sa.CheckConstraint(
            "status IN ('active', 'inactive', 'disabled')", name="provider_status_chk"
        ),
        sa.CheckConstraint("mode IN ('oauth', 'web', 'api')", name="provider_mode_chk"),
        sa.Index("ix_providers_code", "code"),
        sa.Index("ix_providers_country_code", "country_code"),
        sa.Index("ix_providers_status", "status"),
        sa.Index("ix_providers_mode", "mode"),
        sa.Index("ix_providers_regulated", "regulated"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("providers")
    # ### end Alembic commands ###
