"""Add alerts table, update Sellers-Buyers many-to-many relationship, and onboarding workflow changes

Revision ID: e1b9d32e4fc7
Revises: f88e84215dca
Create Date: 2025-11-06 16:21:34.649519

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e1b9d32e4fc7"
down_revision: Union[str, Sequence[str], None] = "f88e84215dca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "buyers",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("is_onboarding_complete", sa.Boolean(), nullable=False),
        sa.Column("business_country", sa.String(length=100), nullable=True),
        sa.Column(
            "business_info", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "shareholders", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("country_code", sa.String(length=10), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_buyers")),
    )
    op.create_unique_constraint(op.f("uq_buyers_email"), "buyers", ["email"])
    op.create_index("ix_buyers_phone", "buyers", ["phone_number"], unique=False)

    op.execute(
        "INSERT INTO buyers (id, is_onboarding_complete, business_country, business_info, shareholders, phone_number, country_code, email, created_at, updated_at) SELECT id, is_onboarding_complete, business_country, business_info, shareholders, phone_number, country_code, email, created_at, updated_at FROM businesses"
    )

    op.create_table(
        "sellers",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("username", sa.String(length=30), nullable=True),
        sa.Column("password_hash", sa.String(length=128), nullable=True),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("country_code", sa.String(length=10), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_access_token", sa.String(length=255), nullable=True),
        sa.Column("access_token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("password_reset_token", sa.String(length=255), nullable=True),
        sa.Column(
            "password_reset_expires_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sellers")),
        sa.UniqueConstraint("email", name=op.f("uq_sellers_email")),
        sa.UniqueConstraint("phone_number", name=op.f("uq_sellers_phone_number")),
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("business_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column(
            "severity_level",
            sa.Enum("high", "normal", "low", name="alert_severity"),
            nullable=False,
        ),
        sa.Column("trigger_source", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["buyers.id"],
            name=op.f("fk_alerts_business_id_buyers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
    )
    op.create_index("ix_alerts_business_id", "alerts", ["business_id"], unique=False)
    op.create_index(
        "ix_alerts_severity_level", "alerts", ["severity_level"], unique=False
    )
    op.create_index("ix_alerts_type", "alerts", ["type"], unique=False)

    op.execute(
        "INSERT INTO sellers (id, username, password_hash, phone_number, country_code, email, is_active, last_login_at, last_access_token, access_token_expires_at, password_reset_token, password_reset_expires_at, created_at, updated_at) SELECT id, username, password_hash, phone_number, country_code, email, is_active, last_login_at, last_access_token, access_token_expires_at, password_reset_token, password_reset_expires_at, created_at, updated_at FROM seller_profiles"
    )

    op.create_table(
        "seller_buyers",
        sa.Column("seller_id", sa.String(length=32), nullable=False),
        sa.Column("buyer_id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["buyer_id"], ["buyers.id"], name=op.f("fk_seller_buyers_buyer_id_buyers")
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["sellers.id"],
            name=op.f("fk_seller_buyers_seller_id_sellers"),
        ),
        sa.PrimaryKeyConstraint("seller_id", "buyer_id", name=op.f("pk_seller_buyers")),
    )
    op.drop_constraint(
        op.f("fk_onboarding_sessions_business_id"),
        "onboarding_sessions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_onboarding_sessions_business_id_buyers"),
        "onboarding_sessions",
        "buyers",
        ["business_id"],
        ["id"],
        ondelete="CASCADE",
    )

    op.drop_table("seller_profiles")
    op.drop_index(op.f("ix_business_email"), table_name="businesses")
    op.drop_index(op.f("ix_business_phone"), table_name="businesses")
    op.drop_table("businesses")
    op.alter_column(
        "connections", "customer_identifier", existing_type=sa.VARCHAR(), nullable=True
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_onboarding_sessions_business_id_buyers"),
        "onboarding_sessions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_onboarding_sessions_business_id"),
        "onboarding_sessions",
        "businesses",
        ["business_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "connections", "customer_identifier", existing_type=sa.VARCHAR(), nullable=False
    )
    op.create_table(
        "businesses",
        sa.Column("id", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
        sa.Column(
            "is_onboarding_complete", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "business_country",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "business_info",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "shareholders",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "phone_number", sa.VARCHAR(length=20), autoincrement=False, nullable=True
        ),
        sa.Column(
            "country_code", sa.VARCHAR(length=10), autoincrement=False, nullable=True
        ),
        sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("businesses_pkey")),
    )
    op.create_index(
        op.f("ix_business_phone"), "businesses", ["phone_number"], unique=False
    )
    op.create_index(op.f("ix_business_email"), "businesses", ["email"], unique=False)
    op.create_table(
        "seller_profiles",
        sa.Column("id", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
        sa.Column(
            "username", sa.VARCHAR(length=30), autoincrement=False, nullable=True
        ),
        sa.Column(
            "password_hash", sa.VARCHAR(length=128), autoincrement=False, nullable=True
        ),
        sa.Column(
            "phone_number", sa.VARCHAR(length=20), autoincrement=False, nullable=True
        ),
        sa.Column(
            "country_code", sa.VARCHAR(length=10), autoincrement=False, nullable=True
        ),
        sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "last_login_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "last_access_token",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "access_token_expires_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "password_reset_token",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "password_reset_expires_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("seller_profiles_pkey")),
        sa.UniqueConstraint(
            "email",
            name=op.f("uq_seller_profiles_email"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        sa.UniqueConstraint(
            "phone_number",
            name=op.f("uq_seller_profiles_phone_number"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.drop_table("seller_buyers")
    op.drop_index("ix_alerts_type", table_name="alerts")
    op.drop_index("ix_alerts_severity_level", table_name="alerts")
    op.drop_index("ix_alerts_business_id", table_name="alerts")
    op.drop_table("alerts")
    op.drop_table("sellers")
    op.drop_constraint(op.f("uq_buyers_email"), "buyers", type_="unique")
    op.drop_index("ix_business_phone", table_name="buyers")
    op.drop_index("ix_business_email", table_name="buyers")
    op.drop_table("buyers")
    # ### end Alembic commands ###
