"""fix bank accounts schema rename connection_id to external_connection_id

Revision ID: fix_bank_accounts_schema
Revises: ab2ffeb94b36
Create Date: 2025-10-30 16:44:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fix_bank_accounts_schema"
down_revision: Union[str, None] = "ab2ffeb94b36"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename connection_id to external_connection_id in bank_accounts table
    op.alter_column(
        "bank_accounts",
        "connection_id",
        new_column_name="external_connection_id",
        existing_type=postgresql.UUID(),
        nullable=False,
    )

    # Add the new connection_id column as FK
    op.add_column(
        "bank_accounts",
        sa.Column(
            "connection_id",
            postgresql.UUID(as_uuid=True),
            nullable=True,  # Allow null initially
        ),
    )

    # Create foreign key constraint for the new connection_id
    op.create_foreign_key(
        op.f("fk_bank_accounts_connection_id_connections"),
        "bank_accounts",
        "connections",
        ["connection_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # Make connection_id not nullable after FK is added
    op.alter_column("bank_accounts", "connection_id", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the new FK constraint
    op.drop_constraint(
        op.f("fk_bank_accounts_connection_id_connections"),
        "bank_accounts",
        type_="foreignkey",
    )

    # Drop the new connection_id column
    op.drop_column("bank_accounts", "connection_id")

    # Rename external_connection_id back to connection_id
    op.alter_column(
        "bank_accounts",
        "external_connection_id",
        new_column_name="connection_id",
        existing_type=postgresql.UUID(),
        nullable=False,
    )

    # Recreate the original FK constraint (though it was pointing to wrong column)
    op.create_foreign_key(
        op.f("fk_bank_accounts_connection_id_connections"),
        "bank_accounts",
        "connections",
        ["connection_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
