"use client";

import { useCallback } from "react";
import { ChevronDown, Download } from "lucide-react";

import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { cn } from "@/lib/utils";

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.rel = "noopener";
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

const ITEM_CLASS =
  "cursor-pointer transition-all duration-200 hover:translate-x-0.5 data-[highlighted]:bg-slate-100 dark:data-[highlighted]:bg-slate-800";

export function ReportExportMenu({
  fileStem,
  className,
}: {
  fileStem: string;
  className?: string;
}) {
  const exportCsv = useCallback(() => {
    const csv =
      "Account,Current month,YTD\nDemo export row,0,0\nGenerated by Factora (demo)";
    const blob = new Blob([csv], { type: "text/csv;charset=utf-8" });
    triggerDownload(blob, `${fileStem}.csv`);
  }, [fileStem]);

  const exportPdf = useCallback(() => {
    const minimalPdf =
      "%PDF-1.4\n1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj\n3 0 obj<</Type/Page/MediaBox[0 0 612 792]/Parent 2 0 R>>endobj\nxref\n0 4\ntrailer<</Size 4/Root 1 0 R>>\nstartxref\n100\n%%EOF";
    const blob = new Blob([minimalPdf], { type: "application/pdf" });
    triggerDownload(blob, `${fileStem}.pdf`);
  }, [fileStem]);

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button
          type="button"
          variant="outline"
          size="sm"
          className={cn(
            "h-9 gap-1.5 border-slate-200 bg-white font-medium shadow-sm dark:border-slate-700 dark:bg-background",
            className
          )}
        >
          <Download className="size-4 opacity-80" aria-hidden />
          Export
          <ChevronDown className="size-3.5 opacity-60" aria-hidden />
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="min-w-[11rem]">
        <DropdownMenuItem className={ITEM_CLASS} onSelect={exportCsv}>
          Export as CSV
        </DropdownMenuItem>
        <DropdownMenuItem className={ITEM_CLASS} onSelect={exportPdf}>
          Export as PDF
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
