/**
 * Rich demo rows for Cash Reconciliation when a SaltEdge customer is resolved.
 * Paired amounts align with seeded bank lines / open-invoice stubs where noted.
 */
import type {
  ReconciliationAutoMatchedPair,
  ReconciliationBookInvoice,
  ReconciliationPendingPair,
} from "@/lib/views/reconciliation";

const EUR = "EUR" as const;

function book(
  o: Omit<ReconciliationBookInvoice, "currency"> & { currency?: "EUR" },
): ReconciliationBookInvoice {
  return { ...o, currency: o.currency ?? EUR };
}

/** Agent auto-applied exact matches (high certainty). */
export const demoReconciliationAutoMatchedPairs: ReconciliationAutoMatchedPair[] =
  [
    {
      id: "auto-1",
      matchLogicSummary: "Exact amount + counterparty token in descriptor",
      transaction: {
        id: "demo-tx-match01",
        date: "2026-04-01",
        amount: 1200,
        currency: EUR,
        merchant: "Acme Ltd",
        rawDescriptor: "SEPA — Acme Ltd — INV-DEMO-0001",
        payerHint: "Acme Ltd",
        bankId: "piraeus",
        maskedAccount: "GR16 ****5678",
      },
      invoice: book({
        id: "inv_demo_1",
        invoiceNumber: "INV-DEMO-0001",
        dueDate: "2026-04-15",
        counterpartyName: "Acme Ltd",
        totalAmount: 1200,
        role: "AR",
        status: "Open",
        glAccount: "1100 — Trade receivables",
        invoiceCategory: "services",
        counterpartyKind: "customer",
        invoiceSummary: "Professional services Q1",
      }),
    },
    {
      id: "auto-2",
      matchLogicSummary: "Exact amount match to open AR",
      transaction: {
        id: "demo-tx-match02",
        date: "2026-04-02",
        amount: 118.4,
        currency: EUR,
        merchant: "Cloud Co",
        rawDescriptor: "SEPA — Cloud Co — INV-DEMO-0002",
        payerHint: "Cloud Co",
        bankId: "eurobank",
        maskedAccount: "GR26 ****4321",
      },
      invoice: book({
        id: "inv_demo_2",
        invoiceNumber: "INV-DEMO-0002",
        dueDate: "2026-04-10",
        counterpartyName: "Cloud Co",
        totalAmount: 118.4,
        role: "AR",
        status: "Open",
        glAccount: "1100 — Trade receivables",
        invoiceCategory: "subscription",
        counterpartyKind: "customer",
        invoiceSummary: "SaaS subscription",
      }),
    },
    {
      id: "auto-3",
      matchLogicSummary: "Wire reference matched to PO",
      transaction: {
        id: "demo-tx-match03",
        date: "2026-03-28",
        amount: 45280,
        currency: EUR,
        merchant: "Nordic Parts AB",
        rawDescriptor: "Wire — Nordic Parts AB — PO-7781",
        payerHint: "Nordic Parts AB",
        bankId: "deutschebank",
        maskedAccount: "DE89 ****1300",
      },
      invoice: book({
        id: "inv_demo_3",
        invoiceNumber: "PO-7781",
        dueDate: "2026-03-30",
        counterpartyName: "Nordic Parts AB",
        totalAmount: 45280,
        role: "AR",
        status: "Open",
        glAccount: "1100 — Trade receivables",
        invoiceCategory: "receivable",
        counterpartyKind: "customer",
        invoiceSummary: "Wholesale parts settlement",
      }),
    },
    {
      id: "auto-4",
      matchLogicSummary: "Descriptor + VAT id heuristic",
      transaction: {
        id: "demo-tx-match04",
        date: "2026-03-22",
        amount: 9900,
        currency: EUR,
        merchant: "Baltic Freight",
        rawDescriptor: "SEPA — Baltic Freight OÜ",
        payerHint: "Baltic Freight OÜ",
        bankId: "revolut",
        maskedAccount: "LT12 ****4400",
      },
      invoice: book({
        id: "inv_demo_4",
        invoiceNumber: "INV-2403-BF",
        dueDate: "2026-03-25",
        counterpartyName: "Baltic Freight OÜ",
        totalAmount: 9900,
        role: "AR",
        status: "Partial",
        glAccount: "1100 — Trade receivables",
        invoiceCategory: "logistics",
        counterpartyKind: "vendor",
        invoiceSummary: "Freight forwarding",
      }),
    },
    {
      id: "auto-5",
      matchLogicSummary: "Stripe payout ↔ acquiring invoice",
      transaction: {
        id: "demo-tx-match05",
        date: "2026-03-19",
        amount: 4200,
        currency: EUR,
        merchant: "Stripe",
        rawDescriptor: "Stripe payout — card acquiring",
        payerHint: "Stripe",
        bankId: "n26",
        maskedAccount: "DE55 ****9012",
      },
      invoice: book({
        id: "inv_demo_5",
        invoiceNumber: "STP-FEB-02",
        dueDate: "2026-03-20",
        counterpartyName: "Stripe",
        totalAmount: 4200,
        role: "AR",
        status: "Open",
        glAccount: "1000 — Cash",
        invoiceCategory: "fee",
        counterpartyKind: "other",
        invoiceSummary: "Card acquiring settlement",
      }),
    },
    {
      id: "auto-6",
      matchLogicSummary: "Exact amount; stable counterparty embedding",
      transaction: {
        id: "demo-tx-match06",
        date: "2026-03-15",
        amount: 3100,
        currency: EUR,
        merchant: "Atlas Cloud",
        rawDescriptor: "SEPA — Atlas Cloud Services IKE",
        payerHint: "Atlas Cloud Services IKE",
        bankId: "eurobank",
        maskedAccount: "GR26 ****4321",
      },
      invoice: book({
        id: "inv_demo_6",
        invoiceNumber: "INV-ACS-1188",
        dueDate: "2026-03-18",
        counterpartyName: "Atlas Cloud Services IKE",
        totalAmount: 3100,
        role: "AR",
        status: "Open",
        glAccount: "4000 — Subscription revenue",
        invoiceCategory: "services",
        counterpartyKind: "customer",
        invoiceSummary: "Managed infrastructure",
      }),
    },
    {
      id: "auto-7",
      matchLogicSummary: "Multi-signal: amount + IBAN country",
      transaction: {
        id: "demo-tx-match07",
        date: "2026-03-12",
        amount: 8750.5,
        currency: EUR,
        merchant: "Helios Analytics",
        rawDescriptor: "Incoming — Helios Analytics OÜ",
        payerHint: "Helios Analytics OÜ",
        bankId: "deutschebank",
        maskedAccount: "DE89 ****1300",
      },
      invoice: book({
        id: "inv_demo_7",
        invoiceNumber: "INV-HEL-552",
        dueDate: "2026-03-14",
        counterpartyName: "Helios Analytics OÜ",
        totalAmount: 8750.5,
        role: "AR",
        status: "Open",
        glAccount: "1100 — Trade receivables",
        invoiceCategory: "services",
        counterpartyKind: "customer",
        invoiceSummary: "Analytics platform fees",
      }),
    },
    {
      id: "auto-8",
      matchLogicSummary: "Confirmed after prior human tweak on category",
      transaction: {
        id: "demo-tx-match08",
        date: "2026-03-08",
        amount: 26400,
        currency: EUR,
        merchant: "Mediterranean Trading",
        rawDescriptor: "SEPA — Mediterranean Trading SA",
        payerHint: "Mediterranean Trading SA",
        bankId: "piraeus",
        maskedAccount: "GR16 ****5678",
      },
      invoice: book({
        id: "inv_demo_8",
        invoiceNumber: "INV-MED-9901",
        dueDate: "2026-03-10",
        counterpartyName: "Mediterranean Trading SA",
        totalAmount: 26400,
        role: "AR",
        status: "Open",
        glAccount: "1100 — Trade receivables",
        invoiceCategory: "receivable",
        counterpartyKind: "customer",
        invoiceSummary: "Goods resale — March",
      }),
    },
  ];

/** Queue: high/medium confidence suggestions, ambiguous, and no-match. */
export const demoReconciliationPendingPairs: ReconciliationPendingPair[] = [
  {
    id: "pend-1",
    aiConfidencePercent: 91,
    aiReasoning:
      "Amount and counterparty align with open invoice; minor date skew (3 days).",
    matchLogicSummary: "Amount exact; issue date within tolerance",
    transaction: {
      id: "demo-tx-match09",
      date: "2026-04-04",
      amount: 5125.25,
      currency: EUR,
      merchant: "Benelux Retail BV",
      rawDescriptor: "FPS — Benelux Retail BV",
      payerHint: "Benelux Retail BV",
      bankId: "deutschebank",
      maskedAccount: "DE89 ****1300",
    },
    invoice: book({
      id: "inv_demo_9",
      invoiceNumber: "INV-BNL-221",
      dueDate: "2026-04-08",
      counterpartyName: "Benelux Retail BV",
      totalAmount: 5125.25,
      role: "AR",
      status: "Open",
      glAccount: "1100 — Trade receivables",
      invoiceCategory: "services",
      counterpartyKind: "customer",
      invoiceSummary: "Implementation milestone 2",
    }),
  },
  {
    id: "pend-2",
    aiConfidencePercent: 86,
    aiReasoning:
      "Strong lexical overlap on renewal pool; confirm contract id before posting.",
    matchLogicSummary: "Descriptor fuzzy-match to renewal bundle",
    transaction: {
      id: "demo-tx-match10",
      date: "2026-04-05",
      amount: 18990,
      currency: EUR,
      merchant: "Enterprise renewal",
      rawDescriptor: "Wire — Enterprise renewal pool",
      payerHint: "Enterprise renewal pool",
      bankId: "eurobank",
      maskedAccount: "GR26 ****4321",
    },
    invoice: book({
      id: "inv_demo_10",
      invoiceNumber: "ERN-2026-Q2",
      dueDate: "2026-04-12",
      counterpartyName: "Enterprise renewal pool",
      totalAmount: 18990,
      role: "AR",
      status: "Open",
      glAccount: "2000 — Deferred revenue",
      invoiceCategory: "subscription",
      counterpartyKind: "customer",
      invoiceSummary: "Multi-entity renewal prepayment",
    }),
  },
  {
    id: "pend-3",
    aiConfidencePercent: 63,
    aiReasoning:
      "Two open invoices share the same gross amount; need allocation or partial apply.",
    matchLogicSummary: "Ambiguous: duplicate amount in AR aging",
    transaction: {
      id: "demo-tx-match11",
      date: "2026-04-06",
      amount: 3333.33,
      currency: EUR,
      merchant: "Misc receipt",
      rawDescriptor: "Ambiguous pool A — misc receipt",
      payerHint: "Unknown payer",
      bankId: "revolut",
      maskedAccount: "LT12 ****4400",
    },
    invoice: book({
      id: "inv_demo_11a",
      invoiceNumber: "MISC-A-01",
      dueDate: "2026-04-09",
      counterpartyName: "Misc customer A",
      totalAmount: 3333.33,
      role: "AR",
      status: "Open",
      glAccount: "1100 — Trade receivables",
      invoiceCategory: "other",
      counterpartyKind: "customer",
      invoiceSummary: "Ad-hoc services",
    }),
    matchCandidates: [
      book({
        id: "inv_demo_11a",
        invoiceNumber: "MISC-A-01",
        dueDate: "2026-04-09",
        counterpartyName: "Misc customer A",
        totalAmount: 3333.33,
        role: "AR",
        status: "Open",
        glAccount: "1100 — Trade receivables",
        invoiceCategory: "other",
        counterpartyKind: "customer",
        invoiceSummary: "Ad-hoc services",
      }),
      book({
        id: "inv_demo_11b",
        invoiceNumber: "MISC-B-02",
        dueDate: "2026-04-09",
        counterpartyName: "Misc customer B",
        totalAmount: 3333.33,
        role: "AR",
        status: "Open",
        glAccount: "1100 — Trade receivables",
        invoiceCategory: "other",
        counterpartyKind: "customer",
        invoiceSummary: "Deposit on account",
      }),
    ],
  },
  {
    id: "pend-4",
    aiConfidencePercent: 58,
    aiReasoning:
      "Counterparty nickname differs from ledger; amount matches one overdue AP.",
    matchLogicSummary: "Fuzzy vendor string",
    transaction: {
      id: "pend-tx-ap-1",
      date: "2026-03-29",
      amount: -2840.5,
      currency: EUR,
      merchant: "Atlassian",
      rawDescriptor: "ATLASSIAN PTY LTD — Jira renewal",
      payerHint: "Factora Ops",
      bankId: "piraeus",
      maskedAccount: "GR16 ****5678",
    },
    invoice: book({
      id: "ap-inv-884",
      invoiceNumber: "ATL-2026-03",
      dueDate: "2026-04-01",
      counterpartyName: "Atlassian Pty Ltd",
      totalAmount: 2840.5,
      role: "AP",
      status: "Overdue",
      glAccount: "2100 — Trade payables",
      invoiceCategory: "payable",
      counterpartyKind: "vendor",
      invoiceSummary: "Jira Cloud — annual seats",
    }),
  },
  {
    id: "pend-5",
    aiConfidencePercent: 44,
    aiReasoning:
      "Possible payroll batch but description shortened by bank; verify against HR run.",
    matchLogicSummary: "Weak text signal",
    transaction: {
      id: "pend-tx-payroll",
      date: "2026-03-25",
      amount: -8200,
      currency: EUR,
      merchant: "Salary batch",
      rawDescriptor: "Salary transfer — Engineering batch",
      payerHint: "Internal",
      bankId: "eurobank",
      maskedAccount: "GR26 ****4321",
    },
    invoice: book({
      id: "je-payroll-march",
      invoiceNumber: "PAY-MAR-26",
      dueDate: "2026-03-25",
      counterpartyName: "Payroll — Engineering",
      totalAmount: 8200,
      role: "AP",
      status: "Open",
      glAccount: "6200 — Payroll expense",
      invoiceCategory: "payable",
      counterpartyKind: "other",
      invoiceSummary: "Semi-monthly payroll accrual",
    }),
  },
  {
    id: "pend-6",
    aiConfidencePercent: 31,
    aiReasoning:
      "No open invoice within 1% of amount; might be a new vendor or card chargeback.",
    matchLogicSummary: "No exact open-item match",
    transaction: {
      id: "pend-tx-orphan",
      date: "2026-03-21",
      amount: -947.13,
      currency: EUR,
      merchant: "Unknown POS",
      rawDescriptor: "CARD PURCHASE — FOREIGN POS 4921",
      payerHint: "Unidentified",
      bankId: "n26",
      maskedAccount: "DE55 ****9012",
    },
    invoice: book({
      id: "suggest-new-ap",
      invoiceNumber: "NEW-VENDOR",
      dueDate: "2026-04-05",
      counterpartyName: "Suggest: create vendor",
      totalAmount: 947.13,
      role: "AP",
      status: "Open",
      glAccount: "6100 — G&A",
      invoiceCategory: "other",
      counterpartyKind: "vendor",
      invoiceSummary: "Agent suggests manual vendor setup before match",
    }),
  },
  {
    id: "pend-7",
    aiConfidencePercent: 22,
    aiReasoning:
      "Inbound amount does not match any AR bucket; could be intercompany or equity.",
    matchLogicSummary: "No candidate above embedding threshold",
    transaction: {
      id: "pend-tx-strange-in",
      date: "2026-03-17",
      amount: 7777.77,
      currency: EUR,
      merchant: "Opaque sender",
      rawDescriptor: "SEPA INST — REF /RFB/UNCATEGORIZED",
      payerHint: "Unknown",
      bankId: "deutschebank",
      maskedAccount: "DE89 ****1300",
    },
    invoice: book({
      id: "placeholder-ar",
      invoiceNumber: "REVIEW-REQ",
      dueDate: "2026-04-01",
      counterpartyName: "Unmatched inflow",
      totalAmount: 7777.77,
      role: "AR",
      status: "Open",
      glAccount: "1000 — Cash",
      invoiceCategory: "other",
      counterpartyKind: "other",
      invoiceSummary: "Create manual AR or reclassify to equity",
    }),
  },
];
